### ISSUE TITLE
[1.16.1-Expanded Storage] Crash on server startup.

### ISSUE THREAD

**Issue by Gbergz** [NinjaPhenix/ForgeMods#6]
This version of the mod for 1.16.1 crashes on server startup.
https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge/files/3002240

**Logs:** https://hastebin.com/wekihilutu.sql

**Forge Version:** 32.0.66
**MC:** 1.16.1

- Gbergz

**Comment by NinjaPhenix** [comment]
Sorry, thought I had tested the mod on a dedicated server before releasing but apparently not. It's easy enough to fix so I'll have a new build out in a few minutes.

**Comment by NinjaPhenix** [comment]
Fixed in latest build: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge/files/3006058
